/// Vietnamese translations for artifact historical context paragraphs.
///
/// These are kept separate due to their length. They are merged into
/// the main translation map at startup.
const Map<String, String> artifactHistoricalContextVi = {
  // IP-001 — Tank 390
  'On the morning of April 30, 1975, Tank 390 — a Chinese-made Type 59 — became the first tank to crash through the main gates of the Independence Palace, a moment captured by photographers and broadcast worldwide. The tank was crewed by soldiers of the 203rd Armored Brigade, with Political Commissar Vũ Đăng Toàn aboard. While Tank 843 actually reached the gates first but became wedged in the smaller side gate, Tank 390 smashed through the central main gate, allowing its crew and soldiers to storm the palace. This event is widely regarded as the defining image of the Fall of Saigon and the reunification of Vietnam.':
      'Vào sáng ngày 30 tháng 4 năm 1975, Xe tăng 390 — loại Type 59 do Trung Quốc sản xuất — trở thành chiếc xe tăng đầu tiên húc đổ cổng chính Dinh Độc Lập, khoảnh khắc được các phóng viên ghi lại và phát sóng khắp thế giới. Kíp xe thuộc Lữ đoàn Tăng — Thiết giáp 203, với Chính trị viên Vũ Đăng Toàn trên xe. Trong khi Xe tăng 843 thực tế đến cổng Dinh trước nhưng bị kẹt ở cổng phụ nhỏ hơn, Xe tăng 390 đã húc tung cổng chính giữa, cho phép kíp xe và bộ đội xông vào Dinh. Sự kiện này được coi là hình ảnh mang tính biểu tượng nhất của ngày Giải phóng Sài Gòn và thống nhất đất nước Việt Nam.',

  // IP-002 — T-54 Tank 843
  'Tank 843, a Soviet-built T-54B, was the first armored vehicle to reach the Independence Palace on April 30, 1975, under the command of Captain Bùi Quang Thận of the 203rd Armored Brigade. After ramming the smaller side gate, the tank stalled momentarily. Bùi Quang Thận then dismounted, sprinted into the palace, climbed to the rooftop, and hoisted the flag of the Provisional Revolutionary Government — an iconic act of liberation. For two decades, Tank 843 was officially credited as the first tank to enter the Palace. In 2012, Tank 843 was officially designated a National Treasure of Vietnam.':
      'Xe tăng 843, loại T-54B do Liên Xô sản xuất, là phương tiện bọc thép đầu tiên tiến đến Dinh Độc Lập vào ngày 30 tháng 4 năm 1975, dưới sự chỉ huy của Đại úy Bùi Quang Thận thuộc Lữ đoàn Tăng — Thiết giáp 203. Sau khi húc vào cổng phụ nhỏ hơn, xe tăng bị chết máy trong giây lát. Bùi Quang Thận lập tức nhảy xuống xe, chạy vào Dinh, leo lên sân thượng và cắm lá cờ của Chính phủ Cách mạng Lâm thời — một hành động giải phóng mang tính biểu tượng. Trong hai thập kỷ, Xe tăng 843 được chính thức ghi nhận là chiếc xe tăng đầu tiên tiến vào Dinh. Năm 2012, Xe tăng 843 được công nhận là Bảo vật Quốc gia của Việt Nam.',

  // IP-003 — UH-1 Helicopter
  'This UH-1 Huey helicopter, formerly of the Republic of Vietnam Air Force, is displayed on the rooftop helipad alongside the bomb marks from the April 8 attack. It was one of the helicopter models used by President Nguyễn Văn Thiệu for official travel. The rooftop helipad was a critical operational feature of the Palace, designed by architect Ngô Viết Thụ to allow rapid evacuation of the President in emergencies. During the final days of the war, helicopters similar to this one were part of the frantic evacuation effort known as Operation Frequent Wind.':
      'Chiếc trực thăng UH-1 Huey này, nguyên thuộc Không quân Việt Nam Cộng hòa, được trưng bày trên sân bay trực thăng sân thượng bên cạnh các vết bom từ cuộc tấn công ngày 8 tháng 4. Đây là một trong những loại trực thăng được Tổng thống Nguyễn Văn Thiệu sử dụng cho các chuyến công du. Sân bay trực thăng trên sân thượng là một tính năng vận hành quan trọng của Dinh, được kiến trúc sư Ngô Viết Thụ thiết kế để cho phép di tản nhanh chóng Tổng thống trong trường hợp khẩn cấp. Trong những ngày cuối cùng của cuộc chiến, các trực thăng tương tự chiếc này là một phần của nỗ lực di tản khẩn cấp được gọi là Chiến dịch Gió Thường Xuyên (Operation Frequent Wind).',

  // IP-004 — Mercedes-Benz 200 W110
  'This Mercedes-Benz 200 (W110 series), manufactured in the 1960s, served as one of the official presidential motorcade vehicles during the tenure of President Nguyễn Văn Thiệu (1967–1975). The car reflects the diplomatic image the Republic of Vietnam government sought to project, using European luxury vehicles for state functions. It is now preserved in the outdoor vehicle display area alongside other presidential transport artifacts, providing visitors a glimpse into the daily operations and ceremonial functions of the presidential administration.':
      'Chiếc Mercedes-Benz 200 (dòng W110) này, sản xuất vào thập niên 1960, là một trong những phương tiện đoàn xe hộ tống chính thức của Tổng thống trong nhiệm kỳ của Tổng thống Nguyễn Văn Thiệu (1967–1975). Chiếc xe phản ánh hình ảnh ngoại giao mà chính quyền Việt Nam Cộng hòa muốn thể hiện, sử dụng xe sang châu Âu cho các sự kiện quốc gia. Hiện chiếc xe được bảo tồn tại khu trưng bày phương tiện ngoài trời cùng với các hiện vật giao thông tổng thống khác, giúp du khách có cái nhìn về hoạt động hàng ngày và các nghi lễ của chính quyền tổng thống.',

  // IP-005 — War Command Bunker Map
  'The strategic war maps displayed in the basement command bunker were essential tools for the South Vietnamese military leadership during the Vietnam War. Designed by engineer Lieutenant Colonel Phan Văn Điển, the bunker was constructed with reinforced concrete walls capable of withstanding aerial bombardment up to 2,000 kg. These maps tracked troop movements, tactical positions, and operational zones across South Vietnam. The bunker served as the nerve center of the war effort, where critical military decisions were made under extreme pressure during the final years of the conflict.':
      'Các bản đồ chiến tranh chiến lược được trưng bày trong hầm chỉ huy tầng hầm là những công cụ thiết yếu cho giới lãnh đạo quân sự miền Nam Việt Nam trong Chiến tranh Việt Nam. Được thiết kế bởi kỹ sư Trung tá Phan Văn Điển, hầm ngầm được xây dựng bằng tường bê tông cốt thép có khả năng chịu được bom đạn trên không lên tới 2.000 kg. Các bản đồ này theo dõi di chuyển của quân đội, vị trí chiến thuật và các vùng tác chiến trên khắp miền Nam Việt Nam. Hầm ngầm là trung tâm thần kinh của nỗ lực chiến tranh, nơi các quyết định quân sự quan trọng được đưa ra dưới áp lực cực đại trong những năm cuối cùng của cuộc xung đột.',

  // IP-006 — F-5E Bombing Marks
  'On the morning of April 8, 1975, First Lieutenant Nguyễn Thành Trung (real name Đinh Khắc Chung) — a covert revolutionary agent embedded within the Republic of Vietnam Air Force — piloted an F-5E Tiger II fighter and broke formation during a bombing mission over Phan Thiết. He turned his aircraft toward Saigon and dropped bombs directly onto the Independence Palace rooftop. Two red circles painted on the terrace mark the exact impact locations. This daring attack was a powerful psychological blow against the Saigon government and signaled the approaching end of the war, just 22 days before the Fall of Saigon.':
      'Vào sáng ngày 8 tháng 4 năm 1975, Trung úy Nguyễn Thành Trung (tên thật là Đinh Khắc Chung) — một điệp viên cách mạng hoạt động bí mật trong Không quân Việt Nam Cộng hòa — đã lái chiếc máy bay chiến đấu F-5E Tiger II và tách khỏi đội hình trong một phi vụ ném bom trên vùng trời Phan Thiết. Ông quay đầu máy bay về hướng Sài Gòn và ném bom trực tiếp lên sân thượng Dinh Độc Lập. Hai vòng tròn đỏ được sơn trên sân thượng đánh dấu chính xác vị trí bom rơi. Cuộc tấn công táo bạo này là một đòn tâm lý mạnh mẽ nhằm vào chính quyền Sài Gòn và báo hiệu sự kết thúc sắp đến của cuộc chiến, chỉ 22 ngày trước ngày Giải phóng Sài Gòn.',

  // IP-007 — Jeep M151A2
  'This M151A2 military jeep was used by revolutionary forces on April 30, 1975, to escort General Dương Văn Minh — the last president of the Republic of Vietnam — from the Independence Palace to the Saigon Radio Station. At the radio station, General Minh read the unconditional surrender declaration, officially ending the Vietnam War. The jeep stands as a tangible link to the final hours of the conflict, when political authority transferred from the Republic of Vietnam to the Provisional Revolutionary Government.':
      'Chiếc xe jeep quân sự M151A2 này được lực lượng cách mạng sử dụng vào ngày 30 tháng 4 năm 1975 để hộ tống Tổng thống Dương Văn Minh — tổng thống cuối cùng của Việt Nam Cộng hòa — từ Dinh Độc Lập đến Đài Phát thanh Sài Gòn. Tại đài phát thanh, Tổng thống Minh đọc tuyên bố đầu hàng vô điều kiện, chính thức kết thúc Chiến tranh Việt Nam. Chiếc xe jeep là một chứng tích hữu hình gắn liền với những giờ phút cuối cùng của cuộc xung đột, khi quyền lực chính trị chuyển giao từ Việt Nam Cộng hòa sang Chính phủ Cách mạng Lâm thời.',

  // IP-008 — Bình Ngô Đại Cáo Lacquer Painting
  'This monumental lacquer painting, measuring approximately 14 meters wide and 9 meters tall, is assembled from 40 individual lacquer panels. Created by artist Nguyễn Văn Minh in 1966 during the Palace construction, the work depicts the "Bình Ngô Đại Cáo" (Great Proclamation upon the Pacification of the Ngô) — the 15th-century proclamation by national hero Nguyễn Trãi declaring Vietnamese independence after defeating the Ming Chinese occupation. The painting uses traditional Vietnamese lacquer techniques with gold leaf, eggshell inlay, and natural pigments, making it one of the most significant lacquer artworks in Vietnam.':
      'Bức tranh sơn mài hoành tráng này, có kích thước khoảng 14 mét chiều rộng và 9 mét chiều cao, được ghép từ 40 tấm sơn mài riêng lẻ. Được họa sĩ Nguyễn Văn Minh sáng tác năm 1966 trong quá trình xây dựng Dinh, tác phẩm mô tả "Bình Ngô Đại Cáo" — bản tuyên cáo thế kỷ 15 của anh hùng dân tộc Nguyễn Trãi tuyên bố nền độc lập của Việt Nam sau khi đánh bại quân Minh xâm lược. Bức tranh sử dụng kỹ thuật sơn mài truyền thống Việt Nam với vàng lá, khảm vỏ trứng và sắc tố tự nhiên, là một trong những tác phẩm sơn mài quan trọng nhất tại Việt Nam.',

  // IP-009 — Cabinet Room Table
  'The Cabinet Room was the formal meeting chamber where the President of the Republic of Vietnam convened with his ministers and senior officials. The room features a large oval conference table covered in green felt, surrounded by executive chairs. It was in this room on the morning of April 30, 1975, that General Dương Văn Minh and his cabinet assembled to prepare the unconditional surrender. When tanks breached the Palace gates, Colonel Bùi Tín of the North Vietnamese Army entered this room to formally accept the surrender.':
      'Phòng Nội các là phòng họp chính thức nơi Tổng thống Việt Nam Cộng hòa triệu tập các bộ trưởng và quan chức cấp cao. Phòng có một chiếc bàn hội nghị hình bầu dục lớn phủ nỉ xanh, bao quanh bởi các ghế hành chính. Chính tại phòng này, vào sáng ngày 30 tháng 4 năm 1975, Tổng thống Dương Văn Minh và nội các đã tập trung để chuẩn bị tuyên bố đầu hàng vô điều kiện. Khi xe tăng húc đổ cổng Dinh, Đại tá Bùi Tín của Quân đội Nhân dân Việt Nam đã bước vào phòng này để chính thức tiếp nhận sự đầu hàng.',

  // IP-010 — The Golden Dragon Tapestry
  'This large tapestry, prominently displayed in the State Banquet Hall on the second floor, depicts a golden dragon — a traditional Vietnamese imperial symbol representing royal authority, prosperity, and the celestial mandate. The State Banquet Hall was used by the President to host state dinners for visiting foreign dignitaries and ambassadors. The room, designed by architect Ngô Viết Thụ, features a blend of mid-century modernism with Vietnamese decorative traditions, and the tapestry serves as its visual centerpiece.':
      'Tấm thảm lớn này, được trưng bày nổi bật tại Phòng Yến tiệc Quốc gia tầng hai, mô tả hình rồng vàng — một biểu tượng hoàng gia truyền thống Việt Nam tượng trưng cho quyền lực vương triều, sự thịnh vượng và thiên mệnh. Phòng Yến tiệc Quốc gia được Tổng thống sử dụng để tổ chức quốc yến tiếp đón các nguyên thủ và đại sứ nước ngoài. Phòng do kiến trúc sư Ngô Viết Thụ thiết kế, kết hợp phong cách hiện đại giữa thế kỷ với truyền thống trang trí Việt Nam, và tấm thảm là điểm nhấn thị giác trung tâm.',

  // IP-011 — Telecommunications Center
  'The Telecommunications Center, located deep within the basement bunker complex, housed the vital communications equipment that connected the presidential command center with military field operations, regional commands, and foreign embassies. The preserved collection includes 1960s-era radio transmitters, telephone switchboards, teletype machines, and encrypted communication devices. This room ensured that the President and his military advisors could maintain command and control even during sustained aerial bombardment of the capital.':
      'Trung tâm Viễn thông, nằm sâu trong tổ hợp hầm ngầm tầng hầm, chứa các thiết bị liên lạc quan trọng kết nối trung tâm chỉ huy tổng thống với các chiến dịch quân sự thực địa, các bộ chỉ huy khu vực và các đại sứ quán nước ngoài. Bộ sưu tập được bảo tồn bao gồm các máy phát sóng vô tuyến, tổng đài điện thoại, máy teletype và thiết bị liên lạc mã hóa từ thập niên 1960. Phòng này đảm bảo rằng Tổng thống và các cố vấn quân sự có thể duy trì quyền chỉ huy và kiểm soát ngay cả trong các đợt ném bom liên tục vào thủ đô.',

  // IP-012 — The Presidential Bed
  'The Presidential Bedroom, located in the private residential quarters on the second floor, has been preserved exactly as it was abandoned when President Nguyễn Văn Thiệu fled Saigon on April 21, 1975 — nine days before the Fall of Saigon. The room contains the original bed, personal furnishings, and period décor, offering visitors a rare and intimate view into the private life of the most powerful figure in the Republic of Vietnam. The preservation of this space reflects the abruptness of the regime change and the chaos of the final days.':
      'Phòng ngủ Tổng thống, nằm trong khu nhà ở riêng tầng hai, được bảo tồn nguyên trạng kể từ khi Tổng thống Nguyễn Văn Thiệu rời Sài Gòn vào ngày 21 tháng 4 năm 1975 — chín ngày trước ngày Giải phóng Sài Gòn. Phòng chứa chiếc giường nguyên bản, đồ nội thất cá nhân và trang trí thời kỳ, mang đến cho du khách một cái nhìn hiếm hoi và thân mật vào đời sống riêng tư của nhân vật quyền lực nhất Việt Nam Cộng hòa. Việc bảo tồn không gian này phản ánh sự đột ngột của sự thay đổi chế độ và sự hỗn loạn của những ngày cuối cùng.',

  // IP-013 — National Security Council Maps
  'The National Security Council strategic war maps, mounted on the walls of the Tactical Command Room in the basement, display the military situation across all four military regions of South Vietnam. These maps were actively updated during the war and show force deployments, territorial boundaries, and key strategic positions. The room served as the operational heart of the South Vietnamese defense strategy, where the President, Joint Chiefs, and American military advisors coordinated the war effort. The maps remain frozen in time, showing the military situation in the war\'s final weeks.':
      'Các bản đồ chiến tranh chiến lược của Hội đồng An ninh Quốc gia, gắn trên tường Phòng Chỉ huy Tác chiến tầng hầm, thể hiện tình hình quân sự trên cả bốn vùng chiến thuật của miền Nam Việt Nam. Các bản đồ này được cập nhật liên tục trong thời chiến và cho thấy sự triển khai lực lượng, ranh giới lãnh thổ và các vị trí chiến lược quan trọng. Phòng này là trung tâm hoạt động của chiến lược phòng thủ miền Nam, nơi Tổng thống, Bộ Tổng Tham mưu và các cố vấn quân sự Mỹ phối hợp nỗ lực chiến tranh. Các bản đồ vẫn đông cứng trong thời gian, thể hiện tình hình quân sự trong những tuần cuối cùng của cuộc chiến.',

  // IP-014 — Basement Cinema Projector
  'The private cinema room in the basement level was used by the Presidential family and close associates for private film screenings. The vintage projector and screening equipment date from the 1960s and represent the lifestyle amenities built into the Palace as both a seat of government and a private residence. The cinema room\'s existence within a fortified basement complex illustrates the unique duality of the Independence Palace — a place where the instruments of war command sat alongside the comforts of domestic life.':
      'Phòng chiếu phim riêng ở tầng hầm được gia đình Tổng thống và những người thân cận sử dụng để xem phim riêng. Máy chiếu và thiết bị chiếu phim cổ điển có niên đại từ thập niên 1960 và đại diện cho các tiện nghi sinh hoạt được xây dựng trong Dinh với tư cách vừa là trụ sở chính phủ vừa là nơi ở riêng. Sự tồn tại của phòng chiếu phim trong tổ hợp hầm ngầm kiên cố minh họa tính chất đặc biệt của Dinh Độc Lập — nơi mà các công cụ chỉ huy chiến tranh nằm bên cạnh những tiện nghi của đời sống gia đình.',

  // IP-015 — Vice President's Desk
  'This finely crafted wooden desk served as the primary workspace of the Vice President of the Republic of Vietnam. Located in the Vice President Office on the second floor, the desk exemplifies traditional Vietnamese woodworking techniques with detailed hand-carved ornamentation. The office was one of several key administrative spaces in the Palace, reflecting the hierarchical structure of the South Vietnamese government. The desk and surrounding furnishings have been preserved in their original arrangement since 1975.':
      'Chiếc bàn gỗ được chế tác tinh xảo này là nơi làm việc chính của Phó Tổng thống Việt Nam Cộng hòa. Đặt tại Văn phòng Phó Tổng thống tầng hai, chiếc bàn thể hiện kỹ thuật chế tác gỗ truyền thống Việt Nam với các hoa văn chạm khắc tay chi tiết. Văn phòng là một trong những không gian hành chính quan trọng trong Dinh, phản ánh cấu trúc thứ bậc của chính quyền miền Nam Việt Nam. Chiếc bàn và đồ nội thất xung quanh được bảo tồn trong cách bố trí nguyên bản kể từ năm 1975.',
};
